services:
  db:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_DB: app
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - ./.data/:/var/lib/postgresql/data
    restart: always
